energymap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("measuring.urls")),
    path("django-admin/", admin.site.urls),
]

measuring/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


def template(src):
    return TemplateView.as_view(template_name=src)


app_name = "measuring"
urlpatterns = [
    path("data", views.data, name="data"),
    path("archives", views.archives, name="archives"),
    path("school/<str:school_name>/", views.school_view, name="school"),
    path("school/<str:school_name>/submit/", views.submit_measurement, name="submit"),
    path("school/<str:school_name>/edit/", views.edit_school, name="edit"),
    path("school/<str:school_name>/archive/", views.archive, name="archive"),
    path("<str:reading_type>_reading/<int:reading_id>", views.reading, name="reading"),
    path("login", views.user_login, name="login"),
    path("admin", views.admin, name="admin"),
    path("logout", views.user_logout, name="logout"),
    path("", template("measuring/info.html"), name="index"),
]

measuring/models.py
from datetime import datetime as dt
from collections import OrderedDict

from django.db import models
from django.utils.timezone import get_current_timezone


class School(models.Model):
    """Each School collects their own data"""

    def __str__(self):
        return self.name

    # School is weakly linked to the User that is used for login
    # by the username field. New Schools will be created automatically
    # when a new non-admin user is created and used.
    username = models.CharField("school short name", max_length=30, primary_key=True)
    name = models.CharField("Full name of the school", max_length=255)
    # Location data for mapping. Defaults to Cavendish Lab
    latitude = models.FloatField(default=52.209132)
    longitude = models.FloatField(default=0.092965)
    elevation = models.FloatField(default=0.0)
    # Archived data is not shown on the main page
    archived = models.BooleanField(default=False)


class Reading(models.Model):
    """A generic series of timed readings"""

    SUNNY = "sunny"
    PARTLY_SUNNY = "partly_sunny"
    CLOUDY = "cloudy"
    RAINY = "rain"
    WEATHER_CHOICES = OrderedDict(
        (
            (SUNNY, "Sunny"),
            (PARTLY_SUNNY, "Partly sunny"),
            (CLOUDY, "Cloudy"),
            (RAINY, "Rainy"),
        )
    )
    WEATHER_SYMBOLS = {
        SUNNY: "fas fa-sun fa-fw",
        PARTLY_SUNNY: "fas fa-cloud-sun fa-fw",
        CLOUDY: "fas fa-cloud fa-fw",
        RAINY: "fas fa-cloud-rain fa-fw",
    }

    class Meta:
        abstract = True
        ordering = ["-datetime"]

    # Proper relationship with the school
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    datetime = models.DateTimeField()
    value = models.FloatField(default=0.0)
    weather = models.CharField(max_length=12, choices=WEATHER_CHOICES.items())

    @property
    def date(self) -> dt.date:
        """Date part of datetime, in configured timezone"""
        return self.datetime.astimezone(get_current_timezone()).date()

    @property
    def time(self) -> dt.time:
        """Time part of datetime, in configured timezone"""
        return self.datetime.astimezone(get_current_timezone()).time()

    @property
    def form_date(self) -> str:
        """Date part of datetime suitable for a form value"""
        return self.datetime.astimezone(get_current_timezone()).strftime("%Y-%m-%d")

    @property
    def form_time(self) -> str:
        """Time part of datetime suitable for a form value"""
        return self.datetime.astimezone(get_current_timezone()).strftime("%H:%M")

    @property
    def weather_symbol(self) -> str:
        """The fontawesome symbol corresponding to the weather."""
        return self.WEATHER_SYMBOLS[self.weather]


class SolarReading(Reading):
    """Data pints for solar intensity measurements"""

    def __str__(self):
        return "solar, {}, {}".format(self.datetime, self.value)


class WindReading(Reading):
    """Data points for wind speed measurements"""

    def __str__(self):
        return "wind, {}, {}".format(self.datetime, self.value)

measuring/views.py
from itertools import count

from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.messages import add_message, ERROR, SUCCESS
from django.http import HttpRequest, HttpResponse, Http404
from django.utils.timezone import make_aware
from django.utils.dateparse import parse_datetime
from django.shortcuts import render, redirect, get_object_or_404

from .data import to_list, to_xy, to_xy_sets
from .models import School, SolarReading, WindReading


def data(request: HttpRequest) -> HttpResponse:
    """Landing page that shows data and all operations."""
    # Overview page will show all the data for all schools at once
    # with the ability to interact with the entire dataset.
    solar_sets = {
        school.name: school.solarreading_set
        for school in School.objects.exclude(archived=True)
    }
    solar_xy = to_xy_sets(solar_sets)
    wind_sets = {
        school.name: school.windreading_set
        for school in School.objects.exclude(archived=True)
    }
    wind_xy = to_xy_sets(wind_sets)
    context = {
        "data": {"wind": {"xy": wind_xy}, "solar": {"xy": solar_xy}},
        "meta": School.objects.exclude(archived=True).all(),
    }
    return render(request, "measuring/data.html", context)


def archives(request: HttpRequest) -> HttpResponse:
    """Display past data in a similar page to the index."""
    solar_sets = {
        school.name: school.solarreading_set
        for school in School.objects.filter(archived=True)
    }
    solar_xy = to_xy_sets(solar_sets)
    wind_sets = {
        school.name: school.windreading_set
        for school in School.objects.filter(archived=True)
    }
    wind_xy = to_xy_sets(wind_sets)
    context = {
        "data": {"wind": {"xy": wind_xy}, "solar": {"xy": solar_xy}},
        "meta": School.objects.filter(archived=True).all(),
        "archives": True,
    }
    return render(request, "measuring/data.html", context)


def user_login(request: HttpRequest) -> HttpResponse:
    """Login page allows user to select a school from a dropdown to login."""
    if request.method == "POST":
        # attempt to login using the submitted form data
        try:
            # Empty values raise an error
            username = request.POST["username"]
            password = request.POST["password"]
            user = authenticate(username=username, password=password)

            # Not able to authenticate, or disabled account
            if user is None or not user.is_active:
                raise ValueError

            # Begin the user's session
            login(request, user)

            # Send admins to the admin interface
            if user.is_staff:
                return redirect("measuring:admin")

            # User is not staff, so must be a school. If this is the first
            # time logging in, ensure a School is created
            School.objects.get_or_create(pk=username, defaults={"name": user.last_name})
            # Logged in for the index page
            return redirect("measuring:school", school_name=username)

        except (KeyError, ValueError):
            # KeyError for missing fields
            # ValueError for invalid credentials
            add_message(request, ERROR, "Invalid username or password")
            return redirect("measuring:login")

    # Not trying to login, so present the login page instead

    # Login options are the school users which are all non-admins
    # in the system
    schools = (
        get_user_model()
        .objects.filter(is_active=True, is_staff=False)
        .order_by("last_name")
        .all()
    )

    context = {"schools": schools}
    return render(request, "measuring/login.html", context)


def user_logout(request: HttpRequest) -> HttpResponse:
    """Clear any login data and return to index"""
    logout(request)
    return redirect("measuring:index")


def school_view(request, school_name: str) -> HttpResponse:
    """Data for a single school, with more details of the school"""
    school = get_object_or_404(School, pk=school_name)
    context = {
        "school_name": school_name,
        "data": {
            "meta": school,
            "wind": to_list(school.windreading_set),
            "solar": to_list(school.solarreading_set),
            "wind_xy": to_xy(school.windreading_set),
            "solar_xy": to_xy(school.solarreading_set),
        },
    }
    return render(request, "measuring/school.html", context)


def submit_measurement(request, school_name: str) -> HttpResponse:
    """Record a new reading for a measurement at the selected school"""
    school = get_object_or_404(School, pk=school_name)

    # Validate if the user can add data. Only the school itself
    # or an admin can update
    if request.user.username != school_name and not request.user.is_staff:
        add_message(request, ERROR, "Must be logged in to record a measurement")
        return redirect("measuring:login")

    # Creation of the data point will raise an error if the form
    # has submitted bad data and then we can follow the error pathway
    try:
        # Choose the right set of measurements to append to
        if request.POST["type"] == "wind":
            dataset = school.windreading_set
        elif request.POST["type"] == "solar":
            dataset = school.solarreading_set
        else:
            raise ValueError

        date_string = "{dt[date]} {dt[time]}".format(dt=request.POST)

        dataset.create(
            value=request.POST["value"],
            datetime=make_aware(parse_datetime(date_string)),
            weather=request.POST["weather"],
        )
    except (KeyError, ValueError, AttributeError):
        add_message(request, ERROR, "Invalid measurement entry!")
        return redirect("measuring:school", school_name=school_name)

    return redirect("measuring:school", school_name=school_name)


def edit_school(request, school_name: str) -> HttpResponse:
    """
    Edit details of the school.

    Allow users to update their location or any other details that might
    need to be updated manually.
    """
    school = get_object_or_404(School, pk=school_name)

    # Validate if the user can add data. Only the school itself
    # or an admin can update
    if request.user.username != school_name and not request.user.is_staff:
        add_message(request, ERROR, "Must be logged in to edit school details")
        return redirect("measuring:login")

    # Any errors will return to the same view with a message banner
    try:
        school.latitude = request.POST["latitude"]
        school.longitude = request.POST["longitude"]
        school.save()
    except (ValueError, KeyError):
        add_message(request, ERROR, "Invalid values for school details!")
        return redirect("measuring:school", school_name=school_name)

    return redirect("measuring:school", school_name=school_name)


def archive(request, school_name: str) -> HttpResponse:
    """
    Move the data into an archived version of the school.
    """
    # Only Admins can archive data
    if not request.user.is_staff:
        add_message(request, ERROR, "Action only available for admins")
        return redirect("measuring:login")

    school = get_object_or_404(School, pk=school_name)

    # Find the next consecutive archive name and create it
    for idx in count():
        archive_name = "{}_a{}".format(school_name, idx)
        if School.objects.filter(username=archive_name):
            continue
        # clone all attributes
        archive_school = School.objects.create(
            pk=archive_name,
            name=school.name,
            latitude=school.latitude,
            longitude=school.longitude,
            archived=True,
        )
        archive_school.save()
        break
    else:
        # stop ide complaints about undefined archive_school
        archive_school = School()

    # Move the data
    school.windreading_set.update(school=archive_school)
    school.solarreading_set.update(school=archive_school)

    add_message(request, SUCCESS, "Archived {}".format(school.name))
    return redirect("measuring:school", school_name=archive_school.pk)


def reading(request, reading_type: int, reading_id: str) -> HttpResponse:
    """Interact with a single measurement."""
    # Must be an existing reading
    if reading_type == "solar":
        value = get_object_or_404(SolarReading, pk=reading_id)
    elif reading_type == "wind":
        value = get_object_or_404(WindReading, pk=reading_id)
    else:
        raise Http404

    # CHeck if it's an update request
    if request.method == "POST":
        user = request.user
        school = value.school
        # Validate if the user can edit data. Only the school itself
        # or an admin can update
        if user.username != school.username and not user.is_staff:
            add_message(request, ERROR, "Must be logged in to modify a measurement")
            return redirect("measuring:reading", reading_type, reading_id)

        # If delete has been clicked then remove entry and return
        # to the school page
        if "delete" in request.POST:
            value.delete()
            add_message(request, SUCCESS, "Measurement deleted!")
            return redirect("measuring:school", school.username)

        # Update with the POSTed values
        date_string = "{dt[date]} {dt[time]}".format(dt=request.POST)
        value.value = request.POST["value"]
        value.datetime = make_aware(parse_datetime(date_string))
        value.weather = request.POST["weather"]
        value.save()
        # Carry on to default view of a value with success message
        add_message(request, SUCCESS, "Measurement updated!")

    context = {"reading_type": reading_type, "reading": value}

    return render(request, "measuring/reading.html", context=context)


def admin(request) -> HttpResponse:
    """
    General admin interface for logging in and basic management
    of the schools.

measuring/templates/measuring/admin.html
{% extends 'measuring/base.html' %}

{% block title %}Administration{% endblock %}

{% block main %}
    {% if messages %}
        {% for message in messages %}
            <div class="message {{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% if mode == "setup" %}
        <div id="admin-init" class="container ml-0">
            <header class="pb-2 mt-4 mb-2">
                <h2>Create initial user</h2>
            </header>
            <form method="post">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="username" class="col-sm-2 col-form-label">Username</label>
                    <div class="col-auto">
                        <input name="username" class="form-control" id="username">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="password" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-auto">
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </div>
            </form>
        </div>
    {% elif mode == "login" %}
        <div id="login-form" class="container ml-0">
            <header class="pb-2 mt-4 mb-2">
                <h2>Login</h2>
            </header>
            <form action="{% url "measuring:login" %}" method="post">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="username" class="col-sm-2 col-form-label">Username</label>
                    <div class="col-auto">
                        <input class="form-control" name="username" id="username">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="password" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-auto">
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </div>
            </form>
        </div>
    {% else %}
        <div class="container ml-0">
            <header class="pb-2 mt-4 mb-2">
                <h1>Administration</h1>
            </header>
            <div>
                <h2>Registered schools</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th>School name</th>
                        <th>Short name</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for school in schools %}
                        <tr>
                            <td>{{ school.last_name }}</td>
                            <td>{{ school.username }}</td>
                            <td><a href="{% url "measuring:archive" school.username %}" class="btn btn-danger">Archive</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div>
                <h2>Register a new school</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="new-school-name" class="col-sm-2">School name</label>
                        <div class="col">
                            <input id="new-school-name" class="form-control" name="new-school-name">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="new-school-username" class="col-sm-2">Short name</label>
                        <div class="col">
                            <input id="new-school-username" class="form-control" name="new-school-username">
                            <small>Short, lowercase with "_" instead of spaces works well.</small>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="new-school-password" class="col-sm-2">Password</label>
                        <div class="col">
                            <input type="password" class="form-control" id="new-school-password"
                                   name="new-school-password">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                    </div>
                </form>
            </div>
            <div>
                <a href="{% url "admin:index" %}">Django site admin interface</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

measuring/templates/measuring/base.html
{% load static %}
<!doctype html>
<html lang="en-gb">
<head>
    {% block head %}
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'measuring/style.css' %}">
        <script
                src="https://code.jquery.com/jquery-3.5.1.min.js"
                integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
                integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
                crossorigin="anonymous"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.13.1/js/all.js"
                integrity="sha256-HkXXtFRaflZ7gjmpjGQBENGnq8NIno4SDNq/3DbkMgo="
                crossorigin="anonymous"></script>
        <script src="{% static "measuring/main.js" %}"></script>
        <title>
            {% block title %}Primary School Energy Mapping Challenge{% endblock %}
        </title>
    {% endblock head %}
    {% block head_extra %}
    {% endblock head_extra %}
</head>
{% block body %}
    <body>
    <div class="container-fluid">
        <div class="row min-vh-md-100">
            {% block nav %}
                <aside class="col-12 col-md-auto p-0 bg-dark">
                    <nav class="navbar navbar-expand navbar-dark flex-md-column flex-row align-items-start py-2 h4">
                        <div class="collapse-toggle navbar-collapse">
                            <ul class="flex-md-column flex-row navbar-nav w-100 justify-content-between">
                                <li class="nav-item">
                                    <a class="nav-link pl-0" href="{% url "measuring:index" %}">
                                        <i class="fas fa-home fa-fw"></i>
                                        <span class="d-none d-md-inline font-weight-bold">Home</span>
                                    </a>
                                </li>
                                <li class="nav-item d-none d-md-inline">
                                    <hr class="border-secondary">
                                </li>
                                {% if user.is_authenticated %}
                                    {% if user.is_staff %}
                                        <li class="nav-item">
                                            <a class="nav-link pl-0"
                                               title="Logged in as admin user: {{ user.username }}">
                                                <i class="fas fa-user-cog fa-fw"></i>
                                                <span class="d-none d-md-inline">{{ user.username }}</span>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link pl-0" href="{% url "measuring:admin" %}">
                                                <i class="fas fa-cog fa-fw"></i>
                                                <span class="d-none d-md-inline font-weight-bold">Admin</span>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li class="nav-item">
                                            <a class="nav-link pl-0" title="Logged in as {{ user.last_name }}">
                                                <i class="fas fa-users fa-fw"></i>
                                                <span class="d-none d-md-inline">{{ user.last_name }}</span>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link pl-0" href="{% url "measuring:school" user.username %}">
                                                <i class="fas fa-tachometer-alt fa-fw"></i>
                                                <span class="d-none d-md-inline font-weight-bold">Measurements</span>
                                            </a>
                                        </li>
                                    {% endif %}
                                    <li class="nav-item">
                                        <a class="nav-link pl-0" href="{% url "measuring:logout" %}">
                                            <i class="fas fa-sign-out-alt fa-fw"></i>
                                            <span class="d-none d-md-inline font-weight-bold">Logout</span>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="nav-item">
                                        <a class="nav-link pl-0" href="{% url "measuring:login" %}">
                                            <i class="fas fa-sign-in-alt fa-fw"></i>
                                            <span class="d-none d-md-inline font-weight-bold">Login</span>
                                        </a>
                                    </li>
                                {% endif %}
                                <li class="nav-item d-none d-md-inline">
                                    <hr class="border-secondary">
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link pl-0" href="{% url "measuring:data" %}">
                                        <i class="fas fa-chart-line fa-fw"></i>
                                        <span class="d-none d-md-inline font-weight-bold">Data</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link pl-0" href="{% url "measuring:archives" %}">
                                        <i class="far fa-folder-open fa-fw"></i>
                                        <span class="d-none d-md-inline font-weight-bold">Archives</span>
                                    </a>
                                </li>
                                <li class="nav-item d-none d-md-inline">
                                    <hr class="border-secondary">
                                </li>
                                <li class="nav-item d-none d-md-inline">
                                    <a class="nav-link pl-0" href="https://www.oe.phy.cam.ac.uk/">
                                        <img src="{% static "measuring/images/logo_cam.png" %}"
                                             alt="University of Cambridge logo" width="180px" class="my-2">
                                    </a>
                                </li>
                                <li class="nav-item d-none d-md-inline">
                                    <a class="nav-link pl-0" href="https://epsrc.ukri.org/">
                                        <img src="{% static "measuring/images/logo_epsrc.png" %}"
                                             alt="EPSRC logo" width="180px" class="my-2">
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </aside>
            {% endblock %}
            {% block content %}
                <main class="col bg-image-random">
                    {% block main %}
                    {% endblock main %}
                </main>
            {% endblock content %}
        </div>
        {% block footer %}
            <footer class="footer">
            </footer>
        {% endblock footer %}
    </div>
    </body>
{% endblock body %}
</html>

measuring/templates/measuring/data.html
{% extends "measuring/base.html" %}

{% block head_extra %}
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock head_extra %}

{% block main %}
    <header class="m-3">
        {% if archives %}
            <h1>Archived data</h1>
        {% else %}
            <h1>Primary School Energy Mapping Challenge</h1>
        {% endif %}
        <hr>
    </header>
    <div class="row">
        <div class="col-auto form-group">
            <label class="h3" for="unit-switch"><i class="fa fa-exchange-alt fa-fw"></i>&nbsp;Change units</label>
            <select id="unit-switch" class="custom-select">
                <option value="watt">Watt</option>
                <option value="kwh">kWh</option>
                <option value="raw">Readings</option>
            </select>
        </div>
        <div id="school-nav" class="col mb-3">
            <h3>Go to school:</h3>
            {% for school in meta %}
                <a class="btn btn-success mb-2" href="{% url "measuring:school" school.username %}">
                    {{ school.name }}
                </a>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div id="data-solar-cumulative" class="col-xl-6 solar-plot-cumulative">
            <h3><i class="fa fa-solar-panel"></i> Cumulative Solar Plot</h3>
            {{ data.solar.xy|json_script:"solar_xy" }}
            <div class="plot-area"></div>
        </div>
        <div id="data-wind-cumulative" class="col-xl-6 wind-plot-cumulative">
            <h3><i class="fa fa-wind"></i> Cumulative Wind Plot</h3>
            {{ data.wind.xy|json_script:"wind_xy" }}
            <div class="plot-area"></div>
        </div>
    </div>
    <div class="row">
        <div id="data-plot-solar" class="col-xl-6 solar-plot-multi">
            <h3><i class="fa fa-solar-panel"></i> Solar Plot</h3>
            {{ data.solar.xy|json_script:"solar_xy" }}
            <div class="plot-area"></div>
        </div>
        <div id="data-plot-wind" class="col-xl-6 wind-plot-multi">
            <h3><i class="fa fa-wind"></i> Wind Plot</h3>
            {{ data.wind.xy|json_script:"wind_xy" }}
            <div class="plot-area"></div>
        </div>
    </div>
{% endblock main %}